# Generated by Django 4.1.4 on 2023-02-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_intrebare_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantaraspuns',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
