# Generated by Django 4.1.4 on 2023-01-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0002_alter_student_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telefon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
