# Generated by Django 4.1.4 on 2023-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0004_alter_student_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cnp',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
