# Generated by Django 4.1.4 on 2023-01-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0005_student_cnp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cnp',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
