# Generated by Django 4.1.4 on 2023-01-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0008_alter_student_cnp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curs_manager.student')),
                ('strada', models.CharField(max_length=20)),
                ('judet', models.CharField(max_length=15)),
                ('cod_postal', models.IntegerField()),
            ],
            bases=('curs_manager.student',),
        ),
    ]
