# Generated by Django 4.1.4 on 2023-01-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0009_adresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresaNoua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strada', models.CharField(max_length=20)),
                ('judet', models.CharField(max_length=15)),
                ('cod_postal', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs_manager.student')),
            ],
        ),
    ]
