# Generated by Django 4.1.4 on 2023-01-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0012_curs_student_cursuri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('an', 'nume', 'prenume')},
        ),
    ]
