# Generated by Django 4.1.4 on 2023-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0013_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('culoare', models.CharField(max_length=10)),
                ('vieti', models.IntegerField(default=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
