# Generated by Django 4.1.4 on 2023-02-21 17:45

from django.db import migrations
from django.db.models import F

def inainte(apps, models):
    print("Inainte")
    Student = apps.get_model("curs_manager", "Student")
    Student.objects.update(an=F('an') + 1)


def inapoi(apps, models):
    print("inapoi")
    Student = apps.get_model("curs_manager", "Student")
    Student.objects.update(an=F('an') - 1)

class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0017_alter_adresa_options_alter_adresanoua_options_and_more'),
    ]

    operations = [
        migrations.RunPython(inainte, inapoi)
    ]
